name: conda_environment_r
channels:
  - conda-forge
dependencies:
  - r-essentials
  - r-tidyverse
  - r-argparse
  - r-devtools
  - r-arrow
  - r-zoo
  - r-lubridate
  - r-yaml
  - r-terra
  - r-sf
  - r-ncdf4
  - r-pacman
